export const config = {
  dogsOptions: [
    {
      id: 0,
      y_landscape: -122,
      x_landscape: -370,
      y_portrait: -165,
      x_portrait: -30,
      rotate: true,
      rotate_portrait: true,
      scale: 0.8,
      scale_portrait: 0.63,
    },
    {
      id: 1,
      y_landscape: -60,
      x_landscape: -5,
      y_portrait: -136,
      x_portrait: 268,
      rotate: true,
      rotate_portrait: false,
      scale: 0.8,
      scale_portrait: 0.5,
    },
    {
      id: 2,
      y_landscape: -132,
      x_landscape: 410,
      y_portrait: 0,
      x_portrait: 168,
      rotate: false,
      rotate_portrait: false,
      scale: 0.75,
      scale_portrait: 0.5,
    },
    {
      id: 3,
      y_landscape: 230,
      x_landscape: -305,
      y_portrait: 82,
      x_portrait: -20,
      rotate: false,
      rotate_portrait: false,
      scale: 1,
      scale_portrait: 0.65,
    },
    {
      id: 4,
      y_landscape: 205,
      x_landscape: 426,
      y_portrait: 180,
      x_portrait: 180,
      rotate: false,
      rotate_portrait: false,
      scale: 0.9,
      scale_portrait: 0.8,
    }
  ]
};